/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CreateTodo: typeof import('./components/createTodo.vue')['default']
    EditTodo: typeof import('./components/editTodo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Teste: typeof import('./components/teste.vue')['default']
    TodoGroup: typeof import('./components/TodoGroup.vue')['default']
    TodoList: typeof import('./components/TodoList.vue')['default']
    ToDoList: typeof import('./components/ToDoList.vue')['default']
    ToDoList1: typeof import('./components/ToDoList1.vue')['default']
    TodoListCards: typeof import('./components/TodoListCards.vue')['default']
    UseTodo: typeof import('./components/useTodo.vue')['default']
  }
}
